"""empty message

Revision ID: 91f2c47d58c1
Revises: 9874738cc6a7
Create Date: 2024-07-22 15:31:33.873289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '91f2c47d58c1'
down_revision: Union[str, None] = '9874738cc6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contactentrymodel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contactentrymodel', schema=None) as batch_op:
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
